openapi: 3.0.0
info:
  version: 0.0.1
  title: Test
  description: My Test
  contact:
    name: Nuno Martins
    email: someone@mail.com
    url: https://ngmmartins.github.io
servers:
  - url: 'http://localhost:{port}/{version}'
    description: Local Development server
    variables:
      port:
        enum:
          - '15500'
        default: '15500'
      version:
        enum:
          - 'v1'
        default: 'v1'
paths:
  /organization:
    get:
      summary: 'Search organizations'
      operationId: searchOrganizations
      tags:
        - Organization Endpoints
      parameters:
        - $ref: '#/components/parameters/contentType'
        - $ref: '#/components/parameters/status'
      responses:
        '200':
          description: 'A list of organizations'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfOrganizations'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      summary: 'Create new Organization'
      operationId: createOrganization
      tags:
        - Organization Endpoints
      parameters:
        - $ref: '#/components/parameters/contentType'
      requestBody:
        description: 'Organization data'
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateOrganizationRequest'
      responses:
        '201':
          description: 'Organization created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  '/organization/{organizationID}':
    get:
      summary: 'Get Organization by ID'
      operationId: getOrganizationByID
      tags:
        - Organization Endpoints
      parameters:
        - $ref: '#/components/parameters/contentType'
        - $ref: '#/components/parameters/organizationID'
      responses:
        '200':
          description: 'The required organization detail'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      summary: 'Update Organization'
      operationId: updateOrganization
      tags:
        - Organization Endpoints
      parameters:
        - $ref: '#/components/parameters/contentType'
        - $ref: '#/components/parameters/organizationID'
      requestBody:
        description: 'Organization data'
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UpdateOrganizationRequest'
      responses:
        '204':
          description: 'No Content'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      summary: 'Delete Organization'
      operationId: deleteOrganization
      tags:
        - Organization Endpoints
      parameters:
        - $ref: '#/components/parameters/contentType'
        - $ref: '#/components/parameters/organizationID'
      responses:
        '204':
          description: 'No Content'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'


components:
  schemas:
    Organization:
      type: object
      required:
        - id
        - name
        - businessName
      properties:
        id:
          type: integer
          format: uint32
          example: 1
        name:
          type: string
          example: 'My Company'
        businessName:
          type: string
          example: 'My Super Company'
        address:
          type: object
          $ref: '#/components/schemas/Address'
    ListOfOrganizations:
      type: array
      items:
        type: object
        $ref: '#/components/schemas/Organization'
    Address:
      type: object
      properties:
        line1:
          type: string
          example: 'Avenida da República'
        line2:
          type: string
          example: 'Nº 458, 2ºEsq'
        city:
          type: string
          example: 'Lisboa'
        state:
          type: string
          example: 'Lisboa'
        postalCode:
          type: string
          example: '1000-427'
        countryCode:
          type: integer
          format: int64
          example: 620
    CreateOrganizationRequest:
      type: object
      required:
        - name
        - businessName
      properties:
        name:
          type: string
          example: 'My Company'
        businessName:
          type: string
          example: 'My Super Company'
        address:
          type: object
          $ref: '#/components/schemas/Address'
    UpdateOrganizationRequest:
      type: object
      required:
        - name
        - businessName
      properties:
        name:
          type: string
          example: 'My Company'
        businessName:
          type: string
          example: 'My Super Company'
        address:
          type: object
          $ref: '#/components/schemas/Address'

    BadRequest:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
          example: 400
        error:
          type: string
          example: 'Bad Request'
        message:
          type: string
          example: 'organizationID in URL path is not a valid uint32'
        path:
          type: string
          example: '/v1/organization/10'
    NotFound:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
          example: 404
        error:
          type: string
          example: 'Not Found'
        message:
          type: string
          example: 'The required resource was not found'
        path:
          type: string
          example: '/v1/organization/10'
    UnprocessableEntity:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
          example: 422
        error:
          type: string
          example: 'Unprocessable Entity'
        message:
          type: string
          example: 'Error rendering the response'
        path:
          type: string
          example: '/v1/organization/10'
    InternalServerError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
          example: 500
        error:
          type: string
          example: 'Internal Server Error'
        message:
          type: string
          example: 'Error occured while getting the resource'
        path:
          type: string
          example: '/v1/organization/10'
    
  parameters:
    contentType:
      name: Content-Type
      in: header
      schema:
        type: string
        example: 'application/json'
    organizationID:
      name: organizationID
      in: path
      description: The id of the organization
      required: true
      example: 1
      schema:
        type: integer
    status:
      name: status
      in: query
      description: Status to filter by, if not provided all status are considered
      required: false
      schema:
        type: string
        example: 'ACTIVE'